server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /api
spring:
  profiles:
    group:
      dev:
        - db-dev
      prod:
        - db-prod
    include:
      - key
      - db
#springdoc swagger
springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui/docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    display-request-duration: true