server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /api
spring:
  profiles:
    group:
      dev:
        - db-dev
      prod:
        - db-prod
    include:
      - key
      - db
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    show-sql: true

#springdoc swagger
springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui/docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    display-request-duration: true

#aws s3 bucket
cloud:
  aws:
    s3:
      bucket: ulvanbucket
    credentials:
      access-key: AKIAQSCG2TLXCKNPB5FO
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

jwt:
  # HS512 알고리즘을 사용함. 해당 알고리즘은 key 값이 최소 512bit 여야함. 따라서 [secret-key]는  64byte 이상이어야 한다.
  secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
  token:
    # 접근 토큰 시간: 5시간 (60*60*5*1000 =18000000)
    access-expiration-time: 18000000
    #갱신토큰시간: 3일  (60*60*24*3*1000=259200000)
    refresh-expiration-time: 259200000